### ISSUE TITLE
关于溯源

### ISSUE THREAD

**Issue by EvanSong77** [Logistic98/rag-omni#4]
我想问一下对于大模型回答的结果溯源的问题，比如经过粗排和精排之后，留下来5个最相关文档，然后让大模型去整理回答，最终能够回复用户问题并把来源返回，我想到两个思路：
1.让大模型根据文档和query回答问题并带出来源id等唯一识别的信息
2.精排的阈值设高一点，只保留top3的文档（低于阈值的一概不要），然后返回直接把保留文档的来源全返回

请问您还有什么比较好的方法吗？

**Comment by Logistic98** [comment]
处理切片时就把文件来源的路径记录下来，然后把相关文档上传到minio，拼个minio的base_url就能拿到文件来源的下载链接。

在重排序之后，我这边通常还会再对切片做一下相关性判断（方式一：用小参数的大模型判断、方式二：训练个小的分类模型去判断），把认为相关的参考资料返回。

**Comment by EvanSong77** [comment]
> 处理切片时就把文件来源的路径记录下来，然后把相关文档上传到minio，拼个minio的base_url就能拿到文件来源的下载链接。
> 
> 在重排序之后，我这边通常还会再对切片做一下相关性判断（方式一：用小参数的大模型判断、方式二：训练个小的分类模型去判断），把认为相关的参考资料返回。

进行相关性判断之后，直接返回所有相关的文档作为回答的来源？
按照您的做法，再加一个判断是否相关的模型，我觉得本质上也是Reranker的一种（设定了阈值），那为啥不微调Reranker模型呢？

**Comment by Logistic98** [comment]
> > 处理切片时就把文件来源的路径记录下来，然后把相关文档上传到minio，拼个minio的base_url就能拿到文件来源的下载链接。
> > 在重排序之后，我这边通常还会再对切片做一下相关性判断（方式一：用小参数的大模型判断、方式二：训练个小的分类模型去判断），把认为相关的参考资料返回。
> 
> 进行相关性判断之后，直接返回所有相关的文档作为回答的来源？ 按照您的做法，再加一个判断是否相关的模型，我觉得本质上也是Reranker的一种（设定了阈值），那为啥不微调Reranker模型呢？

我考虑的是重排序直接使用当下SOTA的开源模型（如bge-reranker-v2-m3），有新版的就直接升级替换，不用再次训练。而且训练个分类模型是相对比较简单的，所需的数据量和标注都容易一些。
